import type { MenuId } from './types'

export type MenuItem =
  | { type: 'separator' }
  | {
      type: 'item'
      label: string
      shortcut?: string
      disabled?: boolean
      submenu?: boolean
      /** 동적 서브메뉴 식별자 (예: 'recent' = 최근 파일 열기) */
      key?: string
      /** 정적 서브메뉴 항목 — hover 시 flyout 으로 표시 */
      children?: MenuItem[]
    }

export const MENU_LABELS: { id: MenuId; label: string }[] = [
  { id: 'file', label: '파일(F)' },
  { id: 'edit', label: '편집(E)' },
  { id: 'image', label: '이미지(I)' },
  { id: 'layer', label: '레이어(L)' },
  { id: 'type', label: '문자(Y)' },
  { id: 'select', label: '선택(S)' },
  { id: 'filter', label: '필터(T)' },
  { id: 'view', label: '보기(V)' },
  { id: 'plugin', label: '플러그인' },
  { id: 'window', label: '창(W)' },
  { id: 'help', label: '도움말(H)' },
]

// 파일 메뉴는 레퍼런스와 동일하게 상세 구현, 나머지는 대표 항목으로 채움
export const MENU_ITEMS: Record<MenuId, MenuItem[]> = {
  file: [
    { type: 'item', label: '새로 만들기...', shortcut: 'Ctrl+N' },
    { type: 'item', label: '열기...', shortcut: 'Ctrl+O' },
    { type: 'item', label: 'Bridge에서 찾아보기(B)...', shortcut: 'Alt+Ctrl+O' },
    { type: 'item', label: '지정 형식...', shortcut: 'Alt+Shift+Ctrl+O' },
    { type: 'item', label: '스마트 오브젝트로 열기...' },
    { type: 'item', label: '최근 파일 열기(T)', submenu: true, key: 'recent' },
    { type: 'separator' },
    { type: 'item', label: '닫기(C)', shortcut: 'Ctrl+W' },
    { type: 'item', label: '모두 닫기', shortcut: 'Alt+Ctrl+W' },
    { type: 'item', label: '기타 항목 닫기', shortcut: 'Alt+Ctrl+P', disabled: true },
    { type: 'item', label: '닫은 후 Bridge로 이동...', shortcut: 'Shift+Ctrl+W' },
    { type: 'item', label: '저장(S)', shortcut: 'Ctrl+S' },
    { type: 'item', label: '다른 이름으로 저장(A)...', shortcut: 'Shift+Ctrl+S' },
    { type: 'item', label: '사본 저장...', shortcut: 'Alt+Ctrl+S' },
    { type: 'item', label: '되돌리기(V)', shortcut: 'F12', disabled: true },
    { type: 'separator' },
    { type: 'item', label: '편집하도록 초대...' },
    { type: 'item', label: '검토용으로 공유' },
    { type: 'item', label: '내보내기(E)', submenu: true },
    { type: 'separator' },
    { type: 'item', label: 'Adobe Stock 검색...' },
    { type: 'item', label: 'Adobe Express 템플릿 검색...' },
    { type: 'item', label: '포함 가져오기(L)...' },
    { type: 'item', label: '연결 가져오기(K)...' },
    { type: 'item', label: '무료 스톡 이미지 배치...' },
    { type: 'item', label: '패키지(G)...', disabled: true },
    { type: 'separator' },
    { type: 'item', label: '자동화(U)', submenu: true },
    { type: 'item', label: '스크립트(R)', submenu: true },
    { type: 'item', label: '가져오기(M)', submenu: true },
    { type: 'separator' },
    { type: 'item', label: '파일 정보(F)...', shortcut: 'Alt+Shift+Ctrl+I' },
    { type: 'item', label: '버전 기록(V)' },
    { type: 'separator' },
    { type: 'item', label: '인쇄(P)...', shortcut: 'Ctrl+P' },
    { type: 'item', label: '한 부 인쇄(Y)', shortcut: 'Alt+Shift+Ctrl+P' },
    { type: 'separator' },
    { type: 'item', label: '종료(X)', shortcut: 'Ctrl+Q' },
  ],
  // 편집 메뉴는 TopMenuBar 에서 Clipboard/Selection 상태에 따라 동적으로 disabled 를 계산해 렌더한다.
  edit: [
    { type: 'item', label: '실행 취소', shortcut: 'Ctrl+Z' },
    { type: 'item', label: '다시 실행', shortcut: 'Shift+Ctrl+Z' },
    { type: 'separator' },
    { type: 'item', label: '오려두기', shortcut: 'Ctrl+X' },
    { type: 'item', label: '복사', shortcut: 'Ctrl+C' },
    { type: 'item', label: '복사 병합', shortcut: 'Shift+Ctrl+C' },
    { type: 'item', label: '붙여넣기', shortcut: 'Ctrl+V' },
    {
      type: 'item',
      label: '붙여넣기 특수',
      submenu: true,
      children: [
        { type: 'item', label: '붙여넣기', shortcut: 'Ctrl+V' },
        { type: 'item', label: '제자리에 붙여넣기', shortcut: 'Shift+Ctrl+V' },
        { type: 'item', label: '안쪽에 붙여넣기', disabled: true },
        { type: 'item', label: '바깥쪽에 붙여넣기', disabled: true },
      ],
    },
    { type: 'item', label: '지우기' },
    { type: 'separator' },
    { type: 'item', label: '칠...', shortcut: 'Shift+F5' },
    { type: 'item', label: '획...' },
    { type: 'item', label: '자유 변형', shortcut: 'Shift+Ctrl+T' },
    { type: 'separator' },
    { type: 'item', label: '환경 설정', submenu: true },
  ],
  image: [
    { type: 'item', label: '모드', submenu: true },
    { type: 'separator' },
    { type: 'item', label: '명도/대비...' },
    { type: 'item', label: '레벨...', shortcut: 'Ctrl+L' },
    { type: 'item', label: '곡선...', shortcut: 'Ctrl+M' },
    { type: 'separator' },
    { type: 'item', label: '이미지 크기...', shortcut: 'Alt+Ctrl+I' },
    { type: 'item', label: '캔버스 크기...', shortcut: 'Alt+Ctrl+C' },
    { type: 'item', label: '이미지 회전', submenu: true },
    { type: 'item', label: '재단...' },
  ],
  layer: [
    { type: 'item', label: '새로 만들기', submenu: true },
    { type: 'item', label: '레이어 복제...' },
    { type: 'item', label: '레이어 삭제' },
    { type: 'separator' },
    { type: 'item', label: '레이어 마스크', submenu: true },
    { type: 'item', label: '고급 오브젝트', submenu: true },
    { type: 'separator' },
    { type: 'item', label: '레이어 그룹화', shortcut: 'Ctrl+G' },
    { type: 'item', label: '아래 레이어와 병합', shortcut: 'Ctrl+E' },
    { type: 'item', label: '배경으로 이미지 병합' },
  ],
  type: [
    { type: 'item', label: '패널', submenu: true },
    { type: 'item', label: '앤티 앨리어스', submenu: true },
    { type: 'item', label: '방향', submenu: true },
    { type: 'separator' },
    { type: 'item', label: '작업 패스 만들기' },
    { type: 'item', label: '모양으로 변환' },
    { type: 'item', label: '문자 레이어 래스터화' },
  ],
  select: [
    { type: 'item', label: '모두', shortcut: 'Ctrl+A' },
    { type: 'item', label: '선택 해제', shortcut: 'Ctrl+D' },
    { type: 'item', label: '다시 선택', shortcut: 'Shift+Ctrl+D' },
    { type: 'item', label: '반전', shortcut: 'Shift+Ctrl+I' },
    { type: 'separator' },
    { type: 'item', label: '모든 레이어', shortcut: 'Alt+Ctrl+A' },
    { type: 'item', label: '피사체 선택' },
    { type: 'item', label: '하늘 선택' },
    { type: 'separator' },
    { type: 'item', label: '선택 및 마스크...', shortcut: 'Alt+Ctrl+R' },
  ],
  filter: [
    { type: 'item', label: '마지막 필터', shortcut: 'Ctrl+F' },
    { type: 'item', label: '고급 필터용으로 변환', disabled: true },
    { type: 'separator' },
    { type: 'item', label: '필터 갤러리...', disabled: true },
    { type: 'separator' },
    {
      type: 'item',
      label: '흐림 효과',
      submenu: true,
      children: [
        { type: 'item', label: '가우시안 흐림 효과...' },
        { type: 'item', label: '동작 흐림 효과...' },
        { type: 'item', label: '표면 흐림 효과...' },
        { type: 'item', label: '상자 흐림 효과...' },
        { type: 'item', label: '방사형 흐림 효과...' },
        { type: 'item', label: '평균' },
        { type: 'item', label: '렌즈 흐림 효과...', disabled: true },
      ],
    },
    {
      type: 'item',
      label: '선명 효과',
      submenu: true,
      children: [
        { type: 'item', label: '고급 선명 효과...' },
        { type: 'item', label: '언샵 마스크...' },
        { type: 'item', label: '하이 패스...' },
      ],
    },
    {
      type: 'item',
      label: '노이즈',
      submenu: true,
      children: [
        { type: 'item', label: '노이즈 추가...' },
        { type: 'item', label: '노이즈 감소...' },
        { type: 'item', label: '중간값...' },
        { type: 'item', label: '먼지와 스크래치...' },
      ],
    },
    {
      type: 'item',
      label: '왜곡',
      submenu: true,
      children: [
        { type: 'item', label: '잔물결...' },
        { type: 'item', label: '돌리기...' },
        { type: 'item', label: '파형...' },
        { type: 'item', label: '지그재그...' },
        { type: 'item', label: '오프셋...' },
      ],
    },
    {
      type: 'item',
      label: '기타',
      submenu: true,
      children: [
        { type: 'item', label: 'Camera Raw 필터...', disabled: true },
        { type: 'item', label: '픽셀 유동화...', disabled: true },
        { type: 'item', label: '유화...', disabled: true },
      ],
    },
  ],
  view: [
    { type: 'item', label: '색상 교정 설정', submenu: true },
    { type: 'separator' },
    { type: 'item', label: '확대', shortcut: 'Ctrl++' },
    { type: 'item', label: '축소', shortcut: 'Ctrl+-' },
    { type: 'item', label: '화면 크기에 맞게', shortcut: 'Ctrl+0' },
    { type: 'item', label: '100%', shortcut: 'Ctrl+1' },
    { type: 'separator' },
    { type: 'item', label: '눈금자 표시', shortcut: 'Ctrl+R' },
    { type: 'item', label: '안내선 표시' },
    { type: 'item', label: '스냅', shortcut: 'Shift+Ctrl+;' },
  ],
  plugin: [
    { type: 'item', label: '플러그인 찾아보기...' },
    { type: 'item', label: '플러그인 관리...' },
    { type: 'separator' },
    { type: 'item', label: '개발용 플러그인', submenu: true },
  ],
  window: [
    { type: 'item', label: '정돈', submenu: true },
    { type: 'item', label: '작업 영역', submenu: true },
    { type: 'separator' },
    { type: 'item', label: '조정' },
    { type: 'item', label: '레이어', shortcut: 'F7' },
    { type: 'item', label: '문자' },
    { type: 'item', label: '색상', shortcut: 'F6' },
    { type: 'item', label: '속성' },
    { type: 'item', label: '채널' },
    { type: 'item', label: '타임라인' },
  ],
  help: [
    { type: 'item', label: '도움말...', shortcut: 'F1' },
    { type: 'item', label: '지원 커뮤니티' },
    { type: 'separator' },
    { type: 'item', label: '시스템 정보...' },
    { type: 'item', label: '정보' },
  ],
}
